#!/usr/bin/env python3
"""
Generates files derived from the plugin layout and config/third_party.json:

- config/packs.json            pack -> skill names, for install.sh and the god-mode CLI
- THIRD_PARTY.md               credits for the whole repository
- plugins/<name>/THIRD_PARTY.md and plugins/<name>/licenses/*
                               credits shipped with each plugin, so a plugin installed
                               on its own still carries the notices MIT and Apache-2.0 require

Usage:
    python3 scripts/build_plugins.py          write the files
    python3 scripts/build_plugins.py --check  exit 1 if any generated file is out of date (CI)
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLUGINS = ROOT / "plugins"
PACKS = {
    "core": ["god-mode-core"],
    "dev": ["god-mode-core", "god-mode-dev"],
    "growth": ["god-mode-core", "god-mode-growth"],
}
OWN_LICENSE = "LICENSE"
GENERATED_HEADER = "<!-- Generated by scripts/build_plugins.py from config/third_party.json. Do not edit by hand. -->\n\n"


def plugin_skills():
    return {
        p.name: sorted(d.name for d in (p / "skills").iterdir() if (d / "SKILL.md").exists())
        for p in sorted(PLUGINS.iterdir()) if (p / ".claude-plugin" / "plugin.json").exists()
    }


def plugin_agents():
    return {p.name: sorted(a.stem for a in (p / "agents").glob("*.md")) for p in sorted(PLUGINS.iterdir())
            if (p / "agents").is_dir()}


def code_list(names):
    return ", ".join(f"`{n}`" for n in sorted(names))


def credits_markdown(meta, skills, agents, license_prefix, archify_license):
    lines = [
        GENERATED_HEADER + "# Third-party components\n",
        "This package bundles skills and agents written by other authors. Each one keeps its original license, "
        f"and the full license texts are in [`{license_prefix}`]({license_prefix}). "
        "Files may have been modified from the upstream versions listed below.\n",
        "| Source | License | Upstream commit | Skills / agents |",
        "| --- | --- | --- | --- |",
    ]
    for src in meta["sources"]:
        own_skills = [s for s in src["skills"] if s in skills]
        own_agents = [a for a in src["agents"] if a in agents]
        if not own_skills and not own_agents:
            continue
        lic_path = archify_license if src["repo"] == "tt-a1i/archify" else license_prefix + Path(src["license_file"]).name
        parts = []
        if own_skills:
            parts.append(f"{len(own_skills)} skills: {code_list(own_skills)}")
        if own_agents:
            parts.append(f"agents: {code_list(own_agents)}")
        lines.append(f"| [{src['repo']}](https://github.com/{src['repo']}) | {src['license']} ([text]({lic_path})) "
                     f"| `{src['commit']}` | {'. '.join(parts)} |")
    lines.append("")
    third = {s for src in meta["sources"] for s in src["skills"]} | {a for src in meta["sources"] for a in src["agents"]}
    original_skills = [s for s in skills if s not in third]
    original_agents = [a for a in agents if a not in third]
    if original_skills or original_agents:
        lines.append("## Original to god-mode\n")
        parts = []
        if original_skills:
            parts.append(f"{len(original_skills)} skills: {code_list(original_skills)}")
        if original_agents:
            parts.append(f"agents: {code_list(original_agents)}")
        lines.append(". ".join(parts) + f". Licensed under the god-mode MIT license ([text]({license_prefix}god-mode-MIT.txt)).\n")
        name_only = [(c["repo"], [s for s in c["skills"] if s in original_skills]) for c in meta["name_only_credits"]]
        name_only = [(r, s) for r, s in name_only if s]
        if name_only:
            refs = "; ".join(f"{code_list(s)} from [{r}](https://github.com/{r})" for r, s in name_only)
            lines.append(f"Some of these reuse only the name of a skill from another project ({refs}). Their text is original.\n")
    notes = [n for n in meta["notes"] if any(s in n for s in skills)]
    if notes:
        lines.append("## Notes\n")
        lines += [f"- {n}" for n in notes]
        lines.append("")
    return "\n".join(lines)


def build():
    meta = json.loads((ROOT / "config" / "third_party.json").read_text(encoding="utf-8"))
    skills_by_plugin = plugin_skills()
    agents_by_plugin = plugin_agents()
    files = {}

    packs = {name: sorted(s for p in plugins for s in skills_by_plugin.get(p, [])) for name, plugins in PACKS.items()}
    packs["all"] = "ALL"
    files[ROOT / "config" / "packs.json"] = json.dumps({"packs": packs}, indent=2) + "\n"

    all_skills = sorted(s for v in skills_by_plugin.values() for s in v)
    all_agents = sorted(a for v in agents_by_plugin.values() for a in v)
    root_md = credits_markdown(meta, all_skills, all_agents, "licenses/",
                               "plugins/god-mode-core/skills/archify/LICENSE")
    removed = "\n".join(f"- `{r['skill']}`, from {r['repo']}: {r['reason']}." for r in meta["removed"])
    root_md += f"\n## Removed for licensing reasons\n\n{removed}\n"
    files[ROOT / "THIRD_PARTY.md"] = root_md

    own_license = (ROOT / OWN_LICENSE).read_text(encoding="utf-8")
    for plugin, skills in skills_by_plugin.items():
        agents = agents_by_plugin.get(plugin, [])
        pdir = PLUGINS / plugin
        files[pdir / "THIRD_PARTY.md"] = credits_markdown(meta, skills, agents, "licenses/", "skills/archify/LICENSE")
        files[pdir / "licenses" / "god-mode-MIT.txt"] = own_license
        for src in meta["sources"]:
            if src["repo"] == "tt-a1i/archify":
                continue
            if any(s in skills for s in src["skills"]) or any(a in agents for a in src["agents"]):
                files[pdir / "licenses" / Path(src["license_file"]).name] = (ROOT / src["license_file"]).read_text(encoding="utf-8")
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = parser.parse_args()
    files = build()
    stale = [p for p, content in files.items() if not p.exists() or p.read_text(encoding="utf-8") != content]
    if args.check:
        if stale:
            print("❌ Generated files are out of date. Run: python3 scripts/build_plugins.py")
            for p in stale:
                print(f"  - {p.relative_to(ROOT)}")
            return 1
        print(f"✅ {len(files)} generated files are up to date.")
        return 0
    for p in stale:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(files[p], encoding="utf-8")
    print(f"Wrote {len(stale)} of {len(files)} generated files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
